package Modelo;
// Generated 19/12/2019 12:47:50 PM by Hibernate Tools 4.3.1



/**
 * TablaEjemplo generated by hbm2java
 */
public class TablaEjemplo  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private Integer edad;

    public TablaEjemplo(Integer id) {
        this.id = id;
    }

    public TablaEjemplo() {
    }

    public TablaEjemplo(String nombre, String apellido, Integer edad) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }




}


